name: Pre-Compile and Lint
on:
  - push
  - pull_request
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1 
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm install
      - name: Compile Source
        run: npm run compile