name: Publish To VSM
on:
  release:
    types:
      - published
jobs:
  main:
    name: Main
    environment:
      name: Visual Studio Marketplace
      url: https://marketplace.visualstudio.com/items?itemName=jeffreylanters.npm-package-version-bumper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1 
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm install
      - name: Install Global Dependencies
        run: npm install vsce --global
      - name: Swap Readme
        run: |
          mv README.md GITHUB.md
          mv MARKETPLACE.md README.md
      - name: Publish Package
        run: vsce publish --pat ${{secrets.VSM_AUTH_TOKEN}}